language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
install:
    "pip install -e '.[coveralls]'"
script:
    "nosetests --with-coverage --cover-branches --cover-package=pgp"
after_success:
    "coveralls"
