language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
    "pip install -e '.[coveralls]'"
script:
    "coverage run --branch --source=pgp nosetests"
after_success:
    "coveralls"
