language: python
python:
  - "3.3"
  - "3.4"
before_install:
    >
      if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      sudo add-apt-repository -y ppa:fkrull/deadsnakes;
      sudo apt-get update;
      sudo apt-get install python3.4-dev;
      fi
install:
    "pip install -e '.[integration,camellia,twofish]'"
script:
    "nosetests"
after_success:
    "coveralls"

sudo: false